site_name: RowBoat docs
site_url: https://docs.rowboatlabs.com
theme:
  name: material
  favicon: img/favicon.ico
nav:
  - Overview:
    - Introduction: index.md
    - Open Source License: license.md
  - Getting started:
    - Installation: installation.md
    - Quickstart: quickstart.md