site_name: RowBoat docs
site_url: https://docs.rowboatlabs.com
theme:
  name: material
  favicon: img/favicon.ico
nav:
  - Overview:
    - Introduction: index.md
    - Open Source License: license.md

  - Getting Started:
    - Option 1 - Open Source: oss_installation.md
    - Option 2 - Hosted App: hosted_setup.md
    - Testing Your Setup: testing.md
  
  - Building in Studio: 
    - Overview: studio_overview.md
    - Create agents: create_agents.md
    - Test chats in the playground: playground.md
    - Add tools: add_tools.md
    - Update agents: update_agents.md
    - Simulate scenarios: simulate.md

  - API & SDK:
    - Using the API: using_the_api.md
    - Using the SDK: using_the_sdk.md
  
  - Concepts:
    - Agents: agents.md
    - Graph: graph.md
    - Tools: tools.md
    - Prompts: prompts.md
    - Data Sources: data_sources.md
